spring:
  application:
    name: eddy-shop

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB


server:
  port: 1999


api:
  prefix: /api/v1

auth:
  token:
    expiration: ${JWT_EXPIRATION_TIME}
    jwtSecret: ${JWT_SECRET}